services:

    stats-db:
      image: postgres:16.1
      environment:
        POSTGRES_DB: stats
        POSTGRES_USER: stats
        POSTGRES_PASSWORD: stats
      ports:
        - "5432:5432"

    ewm-db:
      image: postgres:16.1
      environment:
        POSTGRES_DB: ewm
        POSTGRES_USER: ewm
        POSTGRES_PASSWORD: ewm
      ports:
        - "5434:5432"
      volumes:
        - ./docker-init:/docker-entrypoint-initdb.d