spring:
  application:
    name: collector

  cloud:
    config:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 9090

eureka:
  client:
    enabled: false